
Vagrant.configure("2") do |config|
config.vm.define "web01" do |web01|
web01.vm.box = "generic/ubuntu1804"
web01.vm.network "public_network"
end
web01.vm.provision "shell", inline: <<-SHELL
apt update
apt install apache2 wget unzip -y
systemctl start apache2
systemctl enable apache2
cd /tmp/
wget https://www.tooplate.com/zip-templates/2119_gymso_fitness.zip
unzip -o 2119_gymso_fitness.zip
cp -r 2119_gymso_fitness/* /var/www/html/
systemctl restart apache2
   SHELL

config.vm.define "db01" do |db01|
db01.vm.box = "geerlingguy/centos7"
db01.vm.network "public_network"
end
db01.vm.provision "shell", inline: <<-SHELL
yum install mariadb-server -y
systemctl start mariadb
system ctl enable mariadb

mysql -u root -e 'CREATE DATABASE wordpress;'
mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost IDENTIFIED BY "admin123";'
mysql -u root -e 'FLUSH PRIVILEGES;' 
  SHELL
end